### ISSUE TITLE
Collage moments view on android client

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#10]
**Describe the bug**
When I enter a collage moment on the android client. I dont get the dialoge that asks if I want to upload my picture to the collage.

**To Reproduce**
1. Launch a collage moment
2. Take a picture in the collage moment on the android cilent
3. I get the dialouge: Share to: "Everyone" or "me&friends" but I should get antother dialgue asking me: "Do you want to share to the collage?"

**This is the same for "collage" and "branded collage" moments**

Correct me if I'm wrong on this.

**Expected behavior**
See step 3 abouve.

**Desktop (please complete the following information):**
Production

**Smartphone (please complete the following information):**
Android marshall from onur

**Comment by fredrik-jarnbrost** [comment]
Still reproducible.

Sony Xperia Z5 Compact, Android 7.1.1
