### ISSUE TITLE
Notelet moment - picture or text not appearing on Android client

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#11]
**Describe the bug**
When opening a Notelet moment the picture or text does not appear on Android client

**To Reproduce**
1. On web platform: Set up a notelet moment
2. In the setup screen: Add a picture and text.
3. Launch moment 
4. Open moment on android client
5. See error

**Expected behavior**
See the notelet moment and the text.

**Desktop (please complete the following information):**
Production - chrome

**Smartphone (please complete the following information):**
Android marshall, apk from onur

**Comment by filippoboiani** [comment]
spotted the issue. Fixing
![img_5535 2](https://user-images.githubusercontent.com/17007951/48208877-17cfb580-e374-11e8-82c4-06df1421c02d.PNG)
