### ISSUE TITLE
Implement Crashlytics for IOS

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#110]

**Comment by mawlle** [comment]
I'm not seeing any crashes in the firebase console. 

Is the implementation tested? How do you know that crashes are logged?

**Comment by ConradoMateu** [comment]
Was not working due to configuration, now you can see the reports of Stagecast Dev in the Dashboard. (I did a crash on purpose)

**Comment by mawlle** [comment]
Alright, closing this for now then.
