### ISSUE TITLE
Spotify playlist moment - songs are missing

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#12]
**Describe the bug**
In the spotify playlist moment on the android client: The songs doesn't appear.

**To Reproduce**
0. Set up a spotify playlist moment: url used: https://open.spotify.com/playlist/37i9dQZEVXcO7Ciyw4Ad5B?si=63R2SJKpRWuaKzHUis7kMA
1. Launch a spotify playlist moment 
2. Open on the android client
3. See error.

**Expected behavior**
Exepct to see the songs of the platlist.

**Desktop (please complete the following information):**
Production - chrome

**Smartphone (please complete the following information):**
android marshall - apk from onur.

**Comment by filippoboiani** [comment]
Spotify changed the apis to access the playlist. Before you needed to specify the user in the url. now it is not needed anymore. Please see: https://github.com/stagecast/web-frontend/commit/0d5a8d521f8fc2813bff3e38411ec0ddcb8b56fa#diff-743ec2300a78404d5f371ee2445cb04eL28

**Comment by mawlle** [comment]
A note on this issue: playlist moment works as intended on iOS.

**Comment by filippoboiani** [comment]
Then the api change might not be the issue

**Comment by fredrik-jarnbrost** [comment]
Still reproducable. (Also nothing happens when clicking "Follow Playlist".)

**Comment by fredrik-jarnbrost** [comment]
When opening through a notification the playlist show up. See https://github.com/stagecast/android/issues/254

**Comment by onuryuxcodes** [comment]
I get the playlish on marshall but think I need to check with our spotify account, if we need to update anything. do you have the credentials @markus?

**Comment by mawlle** [comment]
@onuryuxcodes 
Email: hello@stagecast.si
Spotify password: We45=oQK1

**Comment by fredrik-jarnbrost** [comment]
Working on Marshall London, Android 5.0.2. Closing

**Comment by fredrik-jarnbrost** [comment]
Working on Marshall London, Android 5.0.2. Closing
