### ISSUE TITLE
Test before Örebro

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#120]
*This is not a bug but a shared issue. We should all help out to test and verify the functionality for the Örebro case*

***

# Test before Örebro
There are a couple of questions to be verified before Örebro 

It could be anything between 1000 - 6000 users on the premiere

**Expected internet connection**
D3: 100/100
Moderation page: ???

***
## Load test cases
Medium: 200 users upload 2 pictures each in a timeframe of 1 min

Extreme: 6000 users upload 3 pictures each in a timeframe of 1 min.

***
### Server
- [ ] Can it handle API call that would be generated from 6000 users?
- [ ] What happens if that amount of content is uploaded as in the *extreme case*

### D3 media server (displays collage on castle-wall)
- [ ] What happens with the page in the *extreme* load case 
- [ ] Can the internet connection handle the *extreme* load case?

### Moderation page
- [ ] What happens with the page in the *extreme* load case 
- [ ] What internet connection is needed to handle the *extreme* load case?

Question 1: Can the moderation page and the D3 server share the same internet connection?

### Mobile clients
- [ ] What happens to the mobile client if there is a high load on the server?
- Navigate in the app
- Try to upload a picture in the branded collage

**Comment by peffis** [comment]
In the load tester I wrote before I used the “moment” “loadgen” for the uploaded content in order to be able to find and delete it afterwards. Please continue to do so so we don’t generate tons of waste on our server

**Comment by peffis** [comment]
...and there is the stats at https://stats.stagecast.se to look at while running load tests. Especially CPU load and network in/out from the various machines

**Comment by mawlle** [comment]
> In the load tester I wrote before I used the “moment” “loadgen” for the uploaded content in order to be able to find and delete it afterwards. Please continue to do so so we don’t generate tons of waste on our server

Do you mean tag=loadgen or something else?

**Comment by peffis** [comment]
No, I mean like the loadgen script I wrote does it: https://github.com/stagecast/collage_loadgen
Have a look at https://github.com/stagecast/collage_loadgen/blob/482320dc97a2ce749762305a8ab1b44f284b46da/loadgen.py#L67

It uses "loadgen" as momentId in the URL path when it uploads content to the collage using API http://stagecast.se/api/docs#section3.0

As tag you should use the momentClassId that the "collage view" page is configured for so that you can load test the rendering side also.

**Comment by peffis** [comment]
But perhaps this script is what you shall use for the load test. I sent the link to Fredrik J before. I just wanted to point out this in case someone wrote something else - that it is good to use a special moment ID so that we can find and delete useless content afterwards as it can potentially be a lot of it.

**Comment by peffis** [comment]
...and the loadtest script mentioned above has a very simple view of "users". Each user corresponds to ONE thread and will wait a random time (within the time slot specified above), then upload a random file and then quit. So if you want to simulate your two cases 200 users uploads 2 pictures each during you would, with this script, set "n" to 2 * 200 = 400 and "interval" to 60. And for the big test it would be an "n" of 3 * 6000 = 18000 and still an "interval" of 60. 

For userId and password to the script you need at least ONE account that can log in to the production server. For load perspective it does not make a difference if it is 3000 unique users or if it is the "same" user doing all the load generation. 

For the bigger test I think it might actually choke the machine running the test. That amount of threads in Python is "doubtful" and that amount of traffic on one network is "questionable". We don't want the machine generate the load to be the bottleneck in the test so I suggest that, for that test you have a few machines - like everybody have one laptop - and divide "n" between the number of machines.

**Comment by mawlle** [comment]
# Stress test during tech meeting
## Test case 1
We are going to simulate a big stream of pictures that suddenly comes in.
Our extreme case is 6000 users that upload 3 images each within 1 minute. This means a total of 18000 image uploads during 1 minute.

## Preperation
1. Set up the loadgenerator so that you are ready to run it.
Load generator [here](https://github.com/stagecast/collage_loadgen)

2. In order to run the load generator you need to have a folder with pictures to upload.

You can download from our server.
You need a list of contentIDs [here](https://drive.google.com/open?id=1FZ7YU6yYrgsDCodMp4Eub8R3I8F2eqkC) and [here](https://drive.google.com/open?id=1JW37gQ8aduGpu0KmOvdz6kOxtz_JcHXb)

Then you can download pictures by looping through the content list by doing:
```
$ mkdir download
$ for f in `cat files.txt`; do curl -s https://stagecast.se/api/content/$f > download/$f.jpg; done
```


## What to test
What want to use/monitor the following things during the heavy load:
- Monitor the server
- Use the image-moderation page
- Display the branded collage
- Navigate/use the iOS application
- Navigate/use the Android application

## How to test
We will have to spread the load generation over several computers.
This is a proposal of the setup:

### Computer 1 - Mac mini
Internet connection: Hardwire (network: Musikinkubatorn)
Task: Run the branded collage - have a chrome debuger setup to limit the network speed to simulate 100/100

### Computer 2 - 
Internet connection: Hardwire (network: Musikinkubatorn)
Task: Run the moderation page - have a chrome debuger setup to limit the speed to simulate 100/100

### Computer 3 - Fredrik J
Internet connection: Hardwire (network: Musikinkubatorn)
Task: Run the server test program to measure the stats about the api calls.

### Computer 4
Internet connection: Hardwire (network: Musikinkubatorn)
Task: Run loadgen script with n=   interval=60

### Computer 5
Internet connection: Hardwire (network: Musikinkubatorn)
Task: Run loadgen script with n=   interval=60

### Computer 6
Internet connection: Hardwire (network: Musikinkubatorn)
Task: Run loadgen script with n=   interval=60

### Computer 7
Internet connection: Wifi (network: eduroam)
Task: Run loadgen script with n=   interval=60

### Computer 8
Internet connection: Wifi (network: eduroam)
Task: Run loadgen script with n=   interval=60

### Computer 9 - FIippo
Internet connection: Italy
Task: Run loadgen script with n=   interval=60

### Mobile iOS
Internet connection 4G
Task: Navigate in app + try to upload a picture to the branded collage

### Mobile Android
Internet connection 4G
Task: Navigate in app + try to upload a picture to the branded collage

***

## When we are done
Remove all the content that was uploaded during the test.

**Comment by mawlle** [comment]
https://stagecast.se/results/420E01DA-77C8-4F5A-A51E-501D0BFB6F50/moment/EE80895E-0712-4BE0-9263-D85ACE66162A

**Comment by mawlle** [comment]
Next moment:
https://stagecast.se/results/420E01DA-77C8-4F5A-A51E-501D0BFB6F50/moment/1CD16789-C184-4B67-BA88-881FACC1C035

**Comment by mawlle** [comment]
Closing this issue as it's not realted to bug-report. 

In the future we should gather our testing knowlede and routines around this repo: https://github.com/stagecast/testing
