### ISSUE TITLE
IOS is posting the pictures as PNG:s

### ISSUE THREAD

**Issue by peffis** [stagecast/bug-report#124]
**Describe the bug**
All photos uploaded from the IOS app are posted with content type image/jpg but, if you look into them, they are really PNG files. This is wrong in so many ways, but most of all it makes the files many times (in our current resolution about ten times) as large which results in ten times upload time and download time and much more processing needed on the server for uploaded content (not to mention the burden on the user's phone subscription cost). 

As an example: File uploaded (F6E04D41-68D9-4EF3-AB6D-B02B27C3EE8A) has size 1663874 bytes and contains a PNG (even if the phone claims that it has sent a JPG by setting the content type to image/jpg). If I convert that to a jpeg it will get the size 61000 bytes instead. 

**To Reproduce**
1. Upload a picture with the IOS app
2. Download it from the server
3. check the beginning of the file where it reads "PNG" inside the binary

**Expected behavior**
Photos MUST ALWAYS be stored as JPEGs. Any other format does not make sense.

**Comment by mawlle** [comment]
This should be solved now. Reopen if not.
