### ISSUE TITLE
SDK - User Interface

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#129]
1. The user should not be able to look at the app in landscape mode.
2. We should use svg’s for every Moment-icon
3. we should hide the info button under the white text in the box for now
4. Inside of the Momentbox we should write „Flash Moment“ and „Color Moment“ so let’s add the word „Moment“ always. This will expand the Momentbox a bit and will increase the height.
5. Set a margin of 20px top to the headline „Moments“ so that we increase the distance to the black header a bit.

**Comment by peffis** [comment]
1. This is not the SDK's responsibility. Portrait locking is done by the app using the SDK
2. SVG:s needs to be processed at bundling time, so there is no support for pulling an SVG from the server. As we foresee that the icon should be part of the moment information in the future and not stored on the phone this cannot be done
3. It's gone
4. Done
5. Done
