### ISSUE TITLE
Voting moment results page

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#13]
**Describe the bug**
Voting moment results page seems broken.

**To Reproduce**
On web platofrm
1. Set up a voting moment
2. Launch it.
3. On mobile: Open moment and vote for an alternative
4. On web again: Open the results page (press view)
5. See an empty screen with only the red banner.

**Expected behavior**
See the voting results

**Desktop (please complete the following information):**
Production - chrome

**Smartphone (please complete the following information):**
User android client to vote.

**Comment by filippoboiani** [comment]
This might be relates to the moment class filtering. I will get to the bottom of the issue.

**Comment by filippoboiani** [comment]
As expected it's related to the filtering.

**Comment by filippoboiani** [comment]
Merging to staging than production today. There is a PR open waiting for review. I will skip the review to have it immediately
