### ISSUE TITLE
SDK - join moment case

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#134]
**Describe the bug**
There is a case where users might not see an active moment. If the user leaves the app (click home-button) inside ex. a color moment.
Then, if the color moment is stopped and a flash moment is activated in webplatform. When user resumes the app - flash moment should be launched. Right now it's not launched or seen inactive-moment feed

**To Reproduce**
1. Web: Launch a color moment & open it in the mobile app
2. Still inside of color moment - press home button to leave the app.
3. Web: Stop color moment & launc a flash moment
4. Press the app icon to resume app
5. See error: App resumes in the color moment and shut it off imediately. After that the active flash moment is not started or shown in the "active moments" feed.

**Expected behavior**
Flash moment should become active automatically (as it was not seen before) + the moment should be seen in the "active moment feed"

**Smartphone (please complete the following information):**
 - Device: iphone6
 - OS: 11.2.1
 - Version:
Installed from stefans xcode on friday the 11th jan

**Comment by mawlle** [comment]
I'm up for discussion how to solve this. The solution might be to always open the last activated moment. 
There is also a case where a user is in an active moment and a new moment is launched.

**Comment by peffis** [comment]
Yes, this I have seen as well. The problem is that the moment list is not refreshed when the app gets activated again. I guess the proper way is to, when the app is reactivated, close any moment that the user might have open already (it might be still active or closed) load everything and launch the most recent moment.

**Comment by mawlle** [comment]
Yes that sounds like a resonable solution. 

Otherwise I think that there is something like 
```appResume()```
I don't know if that is an easier way to go. Your call.

**Comment by peffis** [comment]
Do test this again in any of the published testflight builds

**Comment by mawlle** [comment]
This issue is tested and not reproducible anymore.

However maybe related issues found is mentioned here #137
