### ISSUE TITLE
SDK - Flash moment

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#135]
**Describe the bug**
Maybe not a bug - The **automatic** flash moment always start with "flash OFF".

More intuitive would be to start with "flash ON"

**To Reproduce**
1. Launch a automatic flash moment
2. Be ready when it start to notice that it will be dark for a couple of seconds.

**Expected behavior**
Start with flash ON

**Smartphone (please complete the following information):**
 - Device: ihpone6
 - OS: 11.2.1
 - stagecastSDK testflight 1.0 (build 5.0)

**Comment by peffis** [comment]
True. I think I actually looked at the iOS code to see what it did. But now that I look at it again I think I must have misread the code in haste as I think it is doing flashOn for duration, then keeps it off for  "interval" and the back again. I'll change this... https://github.com/stagecast/iOS/blob/aed0ed00e6b7e54e08480d0cfde95620f08bbd82/Telia%20Locator/moments/flash/FlashViewController.swift#L182-L195

**Comment by peffis** [comment]
This is actually not what is happening. I see that you have tested with very long durations and intervals flash. When a flash and color moment starts it is going to wait until it reaches the end of a "duration + interval" cycle before it starts the flash loop. So what you interpret at "flash starts off" is actually that is is just syncing and waiting for the next "loop" to start. Then it starts with flash on. The longer you set the "duration and interval" the longer it is likely that you will have to wait before it actually starts to blink as it becomes likely that you are far away from the beginning of a cycle. 

So this is not a bug - it is the intended behaviour. Supposedly one could think of it as a usability bug perhaps that we are not indicating to the user that we are waiting for the sync. We had that before in the simpler user interface but that text was removed in Robins new design where we change between two background pictures.
