### ISSUE TITLE
SDK - flash&color moment / keep screen active

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#136]
**Describe the bug**
Not exactly a bug but something that we should do. If you have an automatic flash for example - you hold up the phone to be part of the moment. After a short while, your screen saver will go on and the flash will be turned off. Would it be possible to keep the screen awake from inside of the sdk? 

This is an issue for the color moment as well.

**To Reproduce**
1. Launch an automatic flash moment
2. Wait to check if screen saver goes on
3. Problem: The flash will stop when the phone launched the screen saver

**Expected behavior**
Keep phone alive in all the moments. This is relevant for ex. color moment as well.

**Smartphone (please complete the following information):**
 - Device: iphone6
 - OS: 11.2.1
testflight StagecastSDK 1.0 build 5.0

**Comment by peffis** [comment]
Fixed. Planned for build 0.0.10
