### ISSUE TITLE
SDK moment not showing up as active case

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#137]
**Describe the bug**
This issue followed after another bug being solved #134. 
An active moment is not showing up in the active moment list. Also moments launched after that happened are not automatically opened.

**To Reproduce**

1. Web: Launch a color moment & open it in the mobile app
2. Still inside of color moment - press home button to leave the app.
3. Web: Stop color moment & launch a flash moment
4. Press the app icon to resume app
5. App resumes in the color moment and shut it off imediately. After that the active flash moment is is started - good!
6. Close the flash moment by clicking x in top right corner 
7. See error: Flash moent is not shown in the "active moments" feed.

8. Also, go ahead and launch another moment (ex a color moment).
9. Moment will appear in the active moment feed but will not be opened automatically on the screen.

**Expected behavior**
See moment in active moment feed  + coming moments should open automatically.

**Smartphone (please complete the following information):**
 - Device: iphone6
 - OS: 11.2.1
testflight stagecastSDK 1.0 build 5.0

**Comment by peffis** [comment]
Fixed (by the fix that solved #145). Will be included in 0.0.10
