### ISSUE TITLE
Merchandise moment on android client.

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#14]
**Describe the bug**
Merchandise moment doesn't load the picture and text

**To Reproduce**
1. Set up merch moment on web platform. I set up this momentclass:
F472D887-1E7C-4147-90EA-825DE365B034
On the setup on the webplatform it looks like this:
![skarmavbild 2018-11-08 kl 10 16 13](https://user-images.githubusercontent.com/18073152/48189029-74fd4400-e33f-11e8-84fd-d37a08919fda.png)

2. When opening on the Android client I get stuck here:
![2018-11-08 10 11 35](https://user-images.githubusercontent.com/18073152/48189082-99f1b700-e33f-11e8-9910-991918cbbcb9.jpg)

**Expected behavior**
See above.

**Screenshots**
See above

**Desktop (please complete the following information):**
Production - chrome

**Smartphone (please complete the following information):**
Marshall android - apk from onur.

**Comment by filippoboiani** [comment]
Fixed closing
