### ISSUE TITLE
SDK - moment not showing in active moment feed (sometimes)

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#140]
**Describe the bug**
After an active moment has been launched (when entering the sdk from parent app) the moment is sometimes not shown in the active moment feed.

**To Reproduce**
1. Have a color moment active
2. Enter the sdk from parent app
3. Moment will automatically be launched 
4. Exit the moment back to SDK startsceen
5. (Sometimes) See error: The active moment is not seen in the active moment feed.

See video of behavior here
https://drive.google.com/open?id=1nAUcgRZrF1rXDX4Ve4FxiIxM-Uo_JhJj

During the whole video the same color moment is active all the time.

**Expected behavior**
Active moment is seen in the active moment feed

**Screenshots**
see video

**Smartphone (please complete the following information):**
 - Device: iphone 6
 - OS: 11.2.1

 - Version stagecastSDK testflight 1.0 build 5.0

***
- Add relevant label (ex if WEB -> add label "web" etc.)

**Comment by peffis** [comment]
Fixed. Will be included in build 0.0.10
