### ISSUE TITLE
Melfest app doesn't respond well to phone text size

### ISSUE THREAD

**Issue by fredrik-jarnbrost** [stagecast/bug-report#143]
**Describe the bug**
When setting the text size to something larger the app clips the content.

**To Reproduce**
1. On the phone, go to Settings -> Display and Brightness -> Text Size, set to max.
2. Start app
3. Content is clipped (icons, texts, etc)

**Expected behavior**
Accessibility should either work completely or not at all.

**Screenshots**
Text size in the middle:
![img_6517](https://user-images.githubusercontent.com/44670720/51252469-323d9500-199c-11e9-9db7-44a17eabec83.PNG)

Text size largest:
![img_6518](https://user-images.githubusercontent.com/44670720/51252470-32d62b80-199c-11e9-8193-869ffe2b84f4.PNG)

**Smartphone (please complete the following information):**
 - Device: iPhone 6S
 - OS: 12.1.2
 - Version: StagecastSDK 1.0 (5.0) (Release Date 15 Jan 2019)

**Comment by peffis** [comment]
Fixed (by disabling font scaling in the app). Fix planned to be included in build 0.0.10
