### ISSUE TITLE
Melfest Flash Moment autoflash should not be clickable

### ISSUE THREAD

**Issue by fredrik-jarnbrost** [stagecast/bug-report#147]
**Describe the bug**
When inside the autoflash Flash Moment you should not be able to manually flash.

**To Reproduce**
1. Launch Flash Moment with autoflash
2. Open moment on device
3. Press the screen
4. The screen and flash lights up

**Expected behavior**
The screen and the flash should not respond to user input when configured as autoflash

**Smartphone (please complete the following information):**
 - Device: iPhone6S
 - OS: iOS 12.1.2
 - Version: Testflight StagecastSDK 1.0 (5.0)

**Comment by peffis** [comment]
Fixed. Fix will be included in build 0.0.10
