### ISSUE TITLE
SDK new picture and telegram momnets doesn't appear in the feed on appResume

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#149]
**Describe the bug**
It seems as the feed is not updated when the user resumes the app. You can launch telegram and picture moments when outside of the app and when resuming they don't appear.

**To Reproduce**
1. Open app
2. Click home button to send app to background
3. Web: Launch telegram OR picture (launch and stop the moment)
4. Resume app
5. See error: The new picture/telegram doesn't appear in feed.

**Expected behavior**
See the new moment

**Smartphone (please complete the following information):**
 - Device: iphone6 & 7
 - OS: 11.2.1 & 12.1

 - Version stagecastSDk testflight 1.0 build 5.0

***
- Add relevant label (ex if WEB -> add label "web" etc.)

**Comment by peffis** [comment]
Fixed. Will be included in build 0.0.10
