### ISSUE TITLE
Picture moment not loading on android client

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#15]
**Describe the bug**
Picture moment not loading on android client

**To Reproduce**
1. Set up a picture moment:
this is the momentClassId: 27E76B03-A865-4FD6-A058-ECF2C5312BB0
This is my view on the webplatform:
![skarmavbild 2018-11-08 kl 10 22 00](https://user-images.githubusercontent.com/18073152/48189385-5a779a80-e340-11e8-9390-8650afedb595.png)

2. On mobile: I get stuck on this screen: 
![2018-11-08 10 20 48](https://user-images.githubusercontent.com/18073152/48189405-6bc0a700-e340-11e8-8ec5-bb7fd7f84587.jpg)

**Expected behavior**
Load the moment

**Screenshots**
See above

**Desktop (please complete the following information):**
Prduction -chrome

**Smartphone (please complete the following information):**
Android marshall apk from onur

**Comment by filippoboiani** [comment]
Fixed, closing
