### ISSUE TITLE
Bug code 9 and 10: App Locale not set correctly

### ISSUE THREAD

**Issue by filippoboiani** [stagecast/bug-report#150]
**Describe the bug**
The app language doesn't change based on the phone locale, but based on the the `default` field defined in `i18n.js`

**To Reproduce**
Launch the app.

**Expected behavior**
Active moments placeholder should have correct design for locale SE. 

**Additional context**

**Comment by filippoboiani** [comment]
The reason depends on the keys used for checking defining the translations. Italian is defined only by  ISO 169-1 code `it` but the detected language will be `it-US` or other variations.

**Comment by filippoboiani** [comment]
The bug can be solved by adding ```i18n.locale = RNLanguages.language.substring(0, 2);``` after the line ```i18n.defaultLocale = 'sv';```

**Comment by peffis** [comment]
Fixed. Will be part of 0.0.11
