### ISSUE TITLE
SDK Layout of fullscreen moments on iphone X

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#151]
**Describe the bug**
The text on top of moments in fullscreen doesn't look so nice in iphone X

**Screenshots**
![screenshot 2019-01-17 at 12 22 21](https://user-images.githubusercontent.com/18073152/51318449-ab032680-1a5a-11e9-975b-50a28ee8295f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
iphone X

**Additional context**
This is most likely true for iphone XS, XR, XS max as well as they have that little top thing on the screen.

***
- Add relevant label (ex if WEB -> add label "web" etc.)

**Comment by Robin9224** [comment]
If possible we should place it with a bigger margin-top. I dont know @peffis if that can be defined only for Iphone X ?

**Comment by peffis** [comment]
Anything is possible. 

So how much lower would you like it to be in case of iPhoneX? It is currently placed 26 pixels down for all phones.

**Comment by peffis** [comment]
36 seems to work fine. I don't think we should move it down further, do you?
![screenshot 2019-01-17 at 16 36 42](https://user-images.githubusercontent.com/2431216/51329659-43f36b00-1a76-11e9-97d6-890494ca9a6e.png)

**Comment by peffis** [comment]
Just give me a go ahead and I will commit this to build 0.0.11

**Comment by peffis** [comment]
Fixed: Moved down to 36. Will be included in 0.0.11
