### ISSUE TITLE
Voting moment - doesn't load in SDK

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#152]
**Describe the bug**
Voting moment doesn't load in SDK

This is the moment class tested.
https://stagecast.se/dashboard/event/launchpad/99C72069-E1D2-496C-BF9A-93EC4E7E3F69/(modal:moment/99C72069-E1D2-496C-BF9A-93EC4E7E3F69/voting/6F0B8ECA-3529-4E6D-90A8-FA8C7EA2D359)

**To Reproduce**
1. Web: Set up voting moment with swedish language and 12 alternatives
2. Launch the moments
3. Mobile: open
4. See error: Voting moment opens but no content is loaded

**Expected behavior**
Voting moment loads

**Screenshots**
Don't get further than this:
![img_eb1674e92439-1](https://user-images.githubusercontent.com/18073152/51324354-cd9d3b80-1a6a-11e9-9648-769b13d00817.jpeg)

**Desktop (please complete the following information):**

 - Browser chrome
 - Version App version: 1.0.2

**Smartphone (please complete the following information):**
 - Device: iphone 6
 - OS: 11.2.1

 - Version stagecastSDK 1.o build 5.0

***
- Add relevant label (ex if WEB -> add label "web" etc.)

**Comment by mawlle** [comment]
I'm able to reproduce this all the time. It never loads for me.

**Comment by Robin9224** [comment]
For Fredrik and me it doesnt work as well. Yesterday it worked fine. Now I get the same result markus has described above.

**Comment by peffis** [comment]
The reason for this is well understood now. An expired token was injected into the voting moment - then nothing shows up. With release 0.0.10 the app makes sure that the token is renewed when needed, so this should not be a problem any more. I also tested to expire my token that I was using on the phone and, before launching the voting moment, the phone realized that the token was old and logged in again to get a new token.
