### ISSUE TITLE
If you launch two or more Moments they will not be displayed in the top area.

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#153]
**Describe the bug**
If you launch two or more Moments, while you are not in the app they will not be displayed in the top area, if you go in the app

**To Reproduce**
1. Go to the Mainscreen of the app
2. Click on the home button to close the app
3. launch on the webplatform two or more moments 
4. Go in the app
5. The last moment will open automatically.
6. Close this Moment
7. No Moments of the ones you have launched on the webplatform are displayed in the top area

**Smartphone (please complete the following information):**
 - Device: [Iphone 7]
 - OS: [e.g. iOS12.1.2]
 - Version [0.0.12]

**Comment by peffis** [comment]
Fixed: Will be included in 0.0.14
