### ISSUE TITLE
Turn off and on the internet bug

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#155]
**Describe the bug**
I tested the following issue that is fixed by Stefan https://github.com/stagecast/bug-report/issues/133
So when I am on the main page with the Moments and the Feed and I turn off the wifi and mobile data I receive directly a message that describes that I dont have internet connection. So that part works. Now I tried to turn on the wifi and mobile data again and wanted to see if i get back the content of the Feed and the launched Moments. So what happened was first that after I turned on the internet the app crashed. After I clicked on the App button again I went directly into an active Moment, after I have closed this one I still saw the „you dont have internet connection message“ I didn’t saw the feed and the active Moments at all. I had to reenter the app again to get back to the main screen of the sdk.

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone7]

 - Version [0.0.12]

**Comment by peffis** [comment]
Yes, it seems to be an issue with the 3rd party library used for detecting network offline status. I'll see if it can be done in a different way.

**Comment by Robin9224** [comment]
As Fredrik told me there are clear instructions in the message that explains that you have to refresh the app after turning on the internet. So I will try that out and see if this works for me.

**Comment by Robin9224** [comment]
So with the instructions „Restart the app after connecting with the internet“ it works for me. BUT still when I am in the app and I loose internet connection the app crashes.

**Comment by peffis** [comment]
Fixed: Will be in release 0.0.14
It's still going to be so that you need to go out of the SDK and in again when you disconnect. But it won't crash hopefully.
