### ISSUE TITLE
Melfest, inconsistent punctuation in no connection message, local sv

### ISSUE THREAD

**Issue by fredrik-jarnbrost** [stagecast/bug-report#157]
**Describe the bug**
The no connection message has inconsistent punctuation. On the first line it has punctuation, on the second it does not (missing the dot.)

**To Reproduce**
1. Turn off wifi and data on your phone.
2. Open the app
3. Message shows up

**Expected behavior**
Punctuation should be consistent.

**Comment by peffis** [comment]
Fixed. Will be included in 0.0.15
