### ISSUE TITLE
Turn off internet bug

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#158]
If you turn off your internet you will get the intended message that will explain to you that you have no internet connection. If you click on the back button in the left top corner and click on „press“ you will not see that internet alert message. Instead you will get stuck on the loading screen. From a user perspective I would expect to see always the alert no matter where I came from.

**Comment by mawlle** [comment]
@Robin9224 put labels and provide version number so that other can reproduce / don't post duplicates.

Label: SDK?
Testflight version: ?

**Comment by mawlle** [comment]
1. If there is no internet when you try to load the app it will just get stuck on "Laddar...".
Here you would like to get the same "no-internet"-message as you get inside of the app.

2. If you get the internet alert "Det verkar vara problem att ansluta .....": You would like to have a button for "Try again". 
(This is maybe something to the future instead.)

**Comment by peffis** [comment]
Fixed: Will be included in 0.0.15. 

Regarding comment 2 with a "Try again". This is not happening in this round.
