### ISSUE TITLE
Article moment is not loading on android client

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#16]
**Describe the bug**
Article moment is not loading on android client

**To Reproduce**
1. Set up an article moment
Monetclassid: 2FE78E76-C68F-49A8-B0F2-D7FE66FD2E5C
My set up screens:

![skarmavbild 2018-11-08 kl 10 27 48](https://user-images.githubusercontent.com/18073152/48189763-349ec580-e341-11e8-9dc6-10a08d834a56.png)

![skarmavbild 2018-11-08 kl 10 27 57](https://user-images.githubusercontent.com/18073152/48189779-3a94a680-e341-11e8-8ad8-99b641e86a98.png)

2. When opening moment on mobile client I get stuck here:

![2018-11-08 10 20 48](https://user-images.githubusercontent.com/18073152/48189746-2a7cc700-e341-11e8-84b8-cffe48aa8ac3.jpg)

**Expected behavior**
Load the moment

**Screenshots**
See above

**Desktop (please complete the following information):**
Production - chrome

**Smartphone (please complete the following information):**
Android Marshall apk from onur

**Comment by filippoboiani** [comment]
All the html-based moments seem to be broken. If the behaviour is the same for both mobile OSs then we know that is a web issue.

**Comment by filippoboiani** [comment]
Fixed. The update will come with the others in only one PR
