### ISSUE TITLE
More efficient loading of moment classes

### ISSUE THREAD

**Issue by peffis** [stagecast/bug-report#3]
We have started to use the new moment class API now in the new version of the app which is great as it makes loading of moments more efficient.

To fully reap the benefits of the moment class API we should do two more things however:
* when you use API http://stagecast.se/api/docs#section4.3 to load a moment class from the backend you should use the CDN host to enable efficient caching of moment classes
* when you use http://stagecast.se/api/docs#section4.3 you should also add the header “Accept-Encoding: gzip” to enable gzip compression of the server response. 

The first bullet will offload our server and make the system more scalable and the second will speed up loading of moment classes and conserve data usage enormously, especially for the large html moments which will compress very well.

I do not foresee this as a big development cost but a large gain for scalability

**Comment by peffis** [comment]
THIS one is actually really important that we prioritise - as seen in the Telia event for instance. The implementation cost is small but the gain is enormous! I cannot stress this enough.

**Comment by filippoboiani** [comment]
The frontend already supports that: removing the tag.

**Comment by mawlle** [comment]
Closing. Done in WEB, iOS, Android projects
