### ISSUE TITLE
Gallery - Missing visual indication

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#30]
If you are on the gallery (guest account) There is no indication if I am on the „everyone“ or „Me&friends“ gallery. 

The „everyone“ section should be marked like this:

<img width="401" alt="bildschirmfoto 2018-11-13 um 11 03 50" src="https://user-images.githubusercontent.com/8388280/48406114-fedc5100-e733-11e8-88b1-54073b44f410.png">

**Comment by mawlle** [comment]
done
