### ISSUE TITLE
„Eventlist - icon“ in the navigation is missing

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#31]
<img width="464" alt="bildschirmfoto 2018-11-13 um 11 06 26" src="https://user-images.githubusercontent.com/8388280/48406206-2e8b5900-e734-11e8-8e9a-a4c9c2f155d3.png">

if you are on the eventlist the eventlist icon should be purple.

If you are on the Profile the eventlist icon should be grey like this:

<img width="437" alt="bildschirmfoto 2018-11-13 um 11 07 04" src="https://user-images.githubusercontent.com/8388280/48406254-44008300-e734-11e8-8bb9-eb2f8f83e8fd.png">

**Comment by mawlle** [comment]
done
