### ISSUE TITLE
Align headline, subline to the left side

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#32]
Please check the figma file to see that the headline and subheadline are aligned on the left side with the eventboxes. The subheadline is as well to far away from the headline. Please check the lineheight.

<img width="367" alt="bildschirmfoto 2018-11-13 um 11 10 52" src="https://user-images.githubusercontent.com/8388280/48406533-0d773800-e735-11e8-96c9-c63c4b26272f.png">

https://www.figma.com/file/Wcjbml9241mfZYrDbEHDGhGq/180727_Stagecast-App?node-id=0%3A297&viewport=2447%2C615%2C1

**Comment by mawlle** [comment]
done
