### ISSUE TITLE
We don’t have the navigation icons anymore when you are inside of an event

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#33]
<img width="405" alt="bildschirmfoto 2018-11-13 um 11 17 30" src="https://user-images.githubusercontent.com/8388280/48406861-d5242980-e735-11e8-8c87-fca151961026.png">

Please have a look in the figma file:

https://www.figma.com/file/Wcjbml9241mfZYrDbEHDGhGq/180727_Stagecast-App?node-id=0%3A576&viewport=1093%2C470%2C1

**Comment by mawlle** [comment]
tested
