### ISSUE TITLE
Back-button goes back to log-in view (or quits the app if already logged in)

### ISSUE THREAD

**Issue by fredrik-jarnbrost** [stagecast/bug-report#36]
**Describe the bug**
Pressing back-button when in either the event list or profile view will go back to log-in view or if already logged in, it will quit the app.

**To Reproduce**
1. Log in
2. View event list or profile view
3. Press OS back-button
4. Goes to log-in view, or if already logged in it will quit the app

**Expected behavior**
Stay in the logged in view / not quitting the app (doing nothing)

**Smartphone (please complete the following information):**
- Device: Sony Xperia Z5 Compact
- OS: Android 7.1.1
- Browser:
- Version: ?

**Comment by onuryuxcodes** [comment]
Fixed.

**Comment by onuryuxcodes** [comment]
To be tested : Login, Sign Up, Log out

**Comment by fredrik-jarnbrost** [comment]
Ok, so I tested a few other apps and peeked on android guidelines, and the app seems to follow those with regards to the back-button in general. 

I have just one question: when logged in and pressing the back-button I get to the log-in view where I can show the password. It seems a bit unsafe, no?

**Comment by onuryuxcodes** [comment]
Yes you should not see login view

**Comment by fredrik-jarnbrost** [comment]
The log-in view is not displayed anymore. Closing.
