### ISSUE TITLE
Invite by e-mail shows link to 404

### ISSUE THREAD

**Issue by fredrik-jarnbrost** [stagecast/bug-report#40]
**Describe the bug**
When inviting friends by e-mail, the link goes to stagecast.github.io/smukfest-appstore-link/ which gives a 404.

**To Reproduce**
1. Log in
2. Click an event
3. Click Add Friends icon
4. Click Invite
5. Choose mail app (I used gmail)
6. The link in the template mail goes to a 404.

**Expected behavior**
The link should be a working app-link.

**Smartphone (please complete the following information):**
- Device: Sony Xperia Z5 Compact
- OS: Android 7.1.1
- Browser:
- Version: ?

**Comment by onuryuxcodes** [comment]
@mawlle right now its smukfest link
https://stagecast.github.io/smukfest-appstore-link/

, what was our stagecast link?

**Comment by mawlle** [comment]
@peffis once this is online (see my slack msg) past URL here.

**Comment by mawlle** [comment]
Here is the new link https://stagecast.se/static/appstore/
@onuryuxcodes 
@ConradoMateu - put this when someone click on the "invite" button in the add friends screen

**Comment by fredrik-jarnbrost** [comment]
Tested. Closing.

I noticed one tiny minor thing, if I had the old link already open in an instance of gmail the old link was still there. But that is probably a gmail thing and out of our control, but it might be good to know.
¯\\\_(ツ)\_/¯
