### ISSUE TITLE
Time triggers: Duration of moment

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#45]
**Describe the bug**
The duration of a moment setting doesn't seem to take effect.
I set a time trigger of a moment with a long duration (8 hours). When I check if the moment was online (after 1 hour) it was not active in the ios client any more.

Url of the moment from web platform:
```https://stagecast.se/dashboard/event/launchpad/7E0D8A54-5068-476A-8112-CC3C8BEDD7FC/(modal:moment/7E0D8A54-5068-476A-8112-CC3C8BEDD7FC/coupon/86563A87-E784-4BF0-9B1B-0282FF7E428C)```

**To Reproduce**
1. Set a time trigger on a moment
2. Choose a long duration (8 hours in my case)
3. See that the moment is not active on the timeline after some time (about 1 hour in my case)

**Expected behavior**
If I set the duration to 8 hours I expect it to be online for 8 hours before stopped.

**Desktop (please complete the following information):**
Chrome

**Smartphone (please complete the following information):**
iOS stagecast 2.1.4(2)

**Comment by peffis** [comment]
I have fixed a few other things on triggers now that could be related. I also tested with duration of 9 seconds and the moment does indeed shut down after the specified 9 seconds. So I would suggest that we do this long-expiration test again now to see if it works. 

I have also removed the expiration timer for manually triggered moments. They should now hopefully be online forever. But this needs to be tested as well.

**Comment by peffis** [comment]
Another explanation could be that there could be some problem with the duration calculation for hourse and minutes as I tested with seconds only now. I will start a long time test and check later if it is alive after some hour or so.

**Comment by peffis** [comment]
You should redo the test you did before before we close this, but the test I just did worked as far as I can tell. I set the moment duration to 4:01:01 which translated to 14461000 ms (see https://www.google.se/search?ei=09PuW_GSJMKQmgXGmoTQBw&q=14461000+ms+in+hours&oq=14461000+ms+in+hours&gs_l=psy-ab.3.0.35i39.3495.3918..4090...0.0..0.366.530.2j3-1......0....1..gws-wiz.XvlCF7FJ99o) and the moment is still active after roughly an hour. I doubt anything else could trigger it to go inactive. 

Then, in the past at least, I think Jakob had some max time for a moment active time when you are still on the timeline. Perhaps the IOS app could also deactivate it locally after some time. This should not change it on the server though, so, if there is something like that still in the IOS phone you should be able to leave and enter the timeline again and see that it is still active when the phone has re-read it from the server.

**Comment by filippoboiani** [comment]
I'm testing all the possible scenarios: I have many active triggers and they seem to last properly. I will make comprehensive tests till Thursday

**Comment by filippoboiani** [comment]
After some further testing the moments seem to last as specified in the duration field. Closing the issue for now
