### ISSUE TITLE
Coupon moment

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#46]
**Describe the bug**
The coupon moment is not showing the actual coupons in on iOS.

Here is one that I used
```https://stagecast.se/dashboard/event/launchpad/7E0D8A54-5068-476A-8112-CC3C8BEDD7FC/(modal:moment/7E0D8A54-5068-476A-8112-CC3C8BEDD7FC/coupon/9591884C-4BF3-4C04-A15E-286A9AF41AB2)```

**To Reproduce**
1. Launch a coupon moment (I had 1 coupon)
2. Launch moment
3. Open on mobile and see error

**Expected behavior**
See coupon

**Screenshots**
![2018-11-14 13 58 33](https://user-images.githubusercontent.com/18073152/48487320-290a3d80-e81e-11e8-8678-2248f5ea8001.png)

**Desktop (please complete the following information):**
Chrome

**Smartphone (please complete the following information):**
iOS stagecast 2.1.4(2)

**Comment by fhyy** [comment]
__Problem:__
When the user had no state, it tried setting the usedList on a Null object which resulted in the shown behaviour. 

__Fix:__
It's fixed by initializing the object to something non-Null if there's no initial state.

**Comment by fhyy** [comment]
Reopened as it should be tested before we close it...

**Comment by mawlle** [comment]
This is solved now
