### ISSUE TITLE
Moments schedule UI/UX

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#49]
**Describe the bug**
When setting / not setting the time schedule of moments the UI acts a bit unexpected.

**To Reproduce**
See this [video](https://drive.google.com/open?id=1bZgBmLJk0cuwKnLTDJ1LkQsNIRPyYL_s)

**Expected behavior**
1. If i'm **not** setting a time I expect "manual" to be choosen and not "schedule" after closing the time-trigger popup

2. If I try to set the time trigger on a second moment it seem to refrecne to the first moment. I expect it to be referencing the moment i choose ofcourse.

**Screenshots**
See video

**Desktop (please complete the following information):**
 - OS: mac
 - Browser chrome v. 70+

**Comment by filippoboiani** [comment]
The triggers you see in the platform are still in beta. The new version will be completely different and is part of the launchpad refactoring coming out in the evening.

**Comment by filippoboiani** [comment]
Closing as the new launchpad with the fix has been released
