### ISSUE TITLE
No text in Notelet Moment

### ISSUE THREAD

**Issue by fredrik-jarnbrost** [stagecast/bug-report#56]
**Describe the bug**
No text show up in Notelet Moment

**To Reproduce**
1. Start Notelet Moment from launchpad

In app:
1. Open Notelet moment (either automatic or from notification)
2. No text is showing

**Expected behavior**
Text should show.

**Screenshots**
![screenshot_20181119-145051](https://user-images.githubusercontent.com/44670720/48711299-369f3900-ec0b-11e8-9b69-1c17795c42cc.png)

**Desktop (please complete the following information):**
- OS: macOS 10.12.6
- Browser: Google Chrome Canary Version 72.0.3615.0 (Official Build) canary (64-bit)

**Smartphone (please complete the following information):**
- Device: Sony Xperia Z5 Compact
- OS: Android 7.1.1

**Comment by fredrik-jarnbrost** [comment]
Working on Marshall London, Android 5.0.2. Closing

**Comment by fredrik-jarnbrost** [comment]
Reopen. Sorry, closed the wrong issue.

**Comment by mawlle** [comment]
tested - closing
