### ISSUE TITLE
Collage Moment not showing in event timeline

### ISSUE THREAD

**Issue by fredrik-jarnbrost** [stagecast/bug-report#60]
**Describe the bug**
The Collage Moment is not showing up in the event timeline.

**To Reproduce**
1. Launch Collage Moment from launchpad
2. Stop the Collage Moment
3. Open event timeline in app
4. No Collage Moment in timeline

**Expected behavior**
See the Collage Moment in timeline

**Desktop (please complete the following information):**
- OS: macOS 10.12.6
- Browser: Google Chrome Canary Version 72.0.3615.0 (Official Build) canary (64-bit)

**Smartphone (please complete the following information):**
- Device: Sony Xperia Z5 Compact
- OS: Android 7.1.1

**Comment by mawlle** [comment]
This is a special case that I can understand leading to some confusion. Right now, filter, collage or branded collage is not shown on the timeline when they are passive. The reason is that they don't have any interesting passive content to show atm.

I'll close this down for now.
