### ISSUE TITLE
Coupon moment - text setup

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#61]
**Describe the bug**
Text change doesn't take effect

**To Reproduce**
1. Setup and launch a coupon moment

**Expected behavior**
See the text that I put in on the web platform

**Screenshots**
![file](https://user-images.githubusercontent.com/18073152/48768841-783aed00-ecba-11e8-9047-4b20da15b915.jpg)

**Desktop (please complete the following information):**
Production
Chrome

**Comment by Robin9224** [comment]
I synched with Markus. The explaination field should be customizable as well. When he tested it he tried to input text that was not displayed in the Moment properly. Thats why he described the bug with the following text: "Text change doesn't take effect“. 

-

So don’t block the feature. Enable it again and look if the text that you input does change in the Moment as well :)

**Comment by mawlle** [comment]
Sorry for the bad description Filippo. :)

**Comment by filippoboiani** [comment]
Oh ok, then we need to sync with @fhyy cause he is not setting the text.

**Comment by fhyy** [comment]
Made subtitle customizable
