### ISSUE TITLE
Text on the Launchpad is not at the right place

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#65]
<img width="1349" alt="bildschirmfoto 2018-11-20 um 16 38 10" src="https://user-images.githubusercontent.com/8388280/48784385-e1365b00-ece2-11e8-828e-89545ef2f038.png">

**Comment by filippoboiani** [comment]
Please specify the browser and version

**Comment by filippoboiani** [comment]
Safari renders :before and :after as elements causing bootstrap cols to wrap (see here: https://stackoverflow.com/questions/34250282/flexbox-wraps-last-column-of-the-first-row-in-safari). 

Fixed and pushing to staging
