### ISSUE TITLE
Sign up / convert of account seem to not set the name of the account correct

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#70]
**Describe the bug**
If I convert / create a new account on web platform it seems like the name of the user is not set correctly. 
This is probably the case because I can't use the credentials to login on iOS but on android. The iOS is different from the android because it checks that the account has a name when you login.

**To Reproduce**

1. Create or convert an account on the stagecast web platform
2. Try to use the credentials to log in on an iOS device.
3. See error - you will not be able to login on iOS

**Expected behavior**
To be able to login. (Name is set when creating / converting account)

**Desktop (please complete the following information):**
 - Browser chrome

**Smartphone (please complete the following information):**
iOS - can't login
Android - can login

**Comment by filippoboiani** [comment]
We might have spotted the real problem. Did you get login error after signing up on the web? or did you get the error after the conversion?

**Comment by mawlle** [comment]
It seems like the problem is in both of the cases.
### On production
1. I created a **new** account on the web platform. I was able to sign in on the webplatform with it and on android, but not on iOS. (the account was tester181818@stagecast.se)

2. Robin went trhoug the conversion process on the webplatform. After doing that he could login on the android app but not the iOS one.

**Comment by mawlle** [comment]
done, closing
