### ISSUE TITLE
Branded Collage - After editing the Moment and launching again the Pictures people take will not show up anymore

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#77]

**Comment by Robin9224** [comment]
Lets have a look at it tomorrow. There is one specific case that we should look at together.

**Comment by filippoboiani** [comment]
All this moment seem to be related to the content upload. That might happen because you are not the owner of the event... It is my first thought because we have never experienced this problem before.

**Comment by filippoboiani** [comment]
All this bugs seem to be related to the content upload. That might happen because you are not the owner of the event... It is my first thought because we have never experienced this problem before.

**Comment by fhyy** [comment]
Just to clarify,
are the old pictures not showing? Or neither the old nor new pictures showing?

**Comment by filippoboiani** [comment]
@robin Are you the owner of the event?

**Comment by filippoboiani** [comment]
After having read the title I realise that this is the standard behaviour for the branded collage: the pictures are tagged with the moment class id. When you edit the moment class, you are actually replacing that with a new one. The picture will belong to the other momentClass
