### ISSUE TITLE
Telegram Moment - Doesn’t display the full text

### ISSUE THREAD

**Issue by Robin9224** [stagecast/bug-report#89]
On Android the Telegram Moment does not display the full text when the text is long.

**Comment by fredrik-jarnbrost** [comment]
@Robin9224 What is the desired behaviour? Now it shows it like the screenshot (it is scrollable, so all the text can be read.)

![screenshot_2018-12-03-15-49-13](https://user-images.githubusercontent.com/44670720/49380997-40e52b00-f713-11e8-8f92-503a5d80d5fc.png)

**Comment by onuryuxcodes** [comment]
Desired behavior : scrollable when active, not scrollable when inactive

**Comment by fredrik-jarnbrost** [comment]
Working on Marshall London, Android 5.0.2. Closing
