### ISSUE TITLE
Collage moment shows no pictures

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#90]
**Describe the bug**
The plain collage moment doesn't show any pictures when I test it with iOS towards the staging platfrom.

**To Reproduce**
1. Set up and launch a collage moment on staging
2. take a picture and upload it with iOS phone
3. See error - no picture seen in collage View-tab

**Expected behavior**
The picture should appear in the collage

**Desktop (please complete the following information):**
 Chrome - staging

**Smartphone (please complete the following information):**
iOS - stagecast DEV - 2.1.4 (5)

**Additional context** 
It wokrs as expected with the Branded collage moment

**Comment by filippoboiani** [comment]
Are you able to see the pictures when you open the config window?

**Comment by mawlle** [comment]
This issue is about the page that opens when you press the "View"-button. The (by user uploaded) pictures doesn't show up in that page.

**Comment by filippoboiani** [comment]
Oh ok, I misunderstood the issue.

**Comment by ConradoMateu** [comment]
is Simething related about your iOS version or is Something about the Webview?

**Comment by mawlle** [comment]
Closing. This is probably a duplicate and  better described in: https://github.com/stagecast/bug-report/issues/118
