### ISSUE TITLE
Coupon Moment looks broken in web-platform when explanation is space character

### ISSUE THREAD

**Issue by fredrik-jarnbrost** [stagecast/bug-report#91]
**Describe the bug**
Coupon Moment looks broken in web-platform when explanation is whitespace.

**To Reproduce**
1. Add Coupon Moment to an event
2. Fill in all the fields, but only put a space in the explanation-field
3. The web-preview to the right shows the coupon graphics to be offset on top of the headline

**Expected behavior**
The coupon graphics should not be offset on top of the headline

**Screenshots**
![screen shot 2018-12-03 at 14 37 37](https://user-images.githubusercontent.com/44670720/49377154-aa603c00-f709-11e8-87b7-dd60da47f839.png)

**Desktop (please complete the following information):**
- OS: macOS 10.12.6
- Browser: Google Chrome Canary Version 72.0.3615.0 (Official Build) canary (64-bit)

**Smartphone (please complete the following information):**
 - Device: Marshall London
 - OS: Android 5.0.2

**Additional context**
It looks fine in the app.
![screenshot_2018-12-03-14-45-46](https://user-images.githubusercontent.com/44670720/49377344-33777300-f70a-11e8-8402-c86e679e1542.png)

**Comment by mawlle** [comment]
done, closing
