### ISSUE TITLE
error code 903 on Android Samsung S7

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#94]
**Describe the bug**
One user reported that she can't install the Stagecast app and get error code 903

**To Reproduce**
Can we use any remote service to run the app on an S7 (if not now, for the future at least.)

**Expected behavior**
Able to install the app.

**Smartphone (please complete the following information):**
 - Device: Androi Samsung S7

**Comment by onuryuxcodes** [comment]
Maybe she can try these steps : https://www.blogtechtips.com/2018/09/27/cant-update-app-error-code-903-google-play-store-android-fix/

**Comment by mawlle** [comment]
will close this for now
