### ISSUE TITLE
Article moment - empty placeholder is seen

### ISSUE THREAD

**Issue by mawlle** [stagecast/bug-report#95]
**Describe the bug**
You get an empty imageplaceholder in the article moment if you set it up without uploading a second picture

**To Reproduce**
Ask Robin how to reproduce this if needed.

**Expected behavior**
No placeholder is shown.

**Screenshots**
![2018-12-04 12 56 41](https://user-images.githubusercontent.com/18073152/49440640-7433c280-f7c4-11e8-8e44-d4eed4910021.png)

**Desktop (please complete the following information):**
Chrome

**Smartphone (please complete the following information):**
Stagecast iOS

**Comment by filippoboiani** [comment]
fixed here: /stagecast/web-frontend/commit/5d0e566ce79f0d2ccc4b37e040cea48ef1311cb3
